### ISSUE TITLE
No Internet?

### ISSUE THREAD

**Issue by PeterStavrou** [AresS31/wirespy#5]
I manage to create a honypot but the computer that connects to it has no internet access.
Kali is running in VirtualBox.

Any ideas?

**Comment by AresS31** [comment]
First step is checking that the Internet-facing interface that you have setup for the Honeypot has got Internet connectivity. Then you can check on your client device that it has received an IP address.

Can you also please paste the result of these commands:
`cat /proc/sys/net/ipv4/ip_forward`
`iptables -L -n -v -t nat`

Thanks
Alex

**Comment by PeterStavrou** [comment]
Thanks Alex!
This was a user issue please close this ticket. Wirespy works perfectly! :)
